# Generated by Django 5.0.2 on 2024-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='ключ'),
        ),
    ]
