# Generated by Django 5.0.2 on 2024-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликовано'),
        ),
    ]
