# Generated by Django 5.0.2 on 2024-04-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_products_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': [('set_published', 'can publish products'), ('change_description', 'can change description'), ('change_category', 'can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
